fix: false               # default: false
parallel: false          # default: false
# format: progress        # default: Standard::Formatter
# ruby_version: 3.0       # default: RUBY_VERSION
# default_ignores: false  # default: true

ignore:                 # default: []
  - 'app/**/*':
    - Rails/HasAndBelongsToMany
  - 'vendor/**/*'

plugins:                # default: []
  - standard-rails

extend_config:                # default: []
  # - .standard_ext.yml