#version: '3.7'
services:
  db:
    image: 'postgres:latest'
    volumes:
      - postgres:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres

  rails:
    build:
      context: ./docker/rails
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - ./sww-backend:/app
      - bundle-api:/usr/local/bundle
    depends_on:
      - db

  react:
    build:
      context: ./
    image: node:23-alpine
    volumes:
      - ./sww-frontend:/client
      - ./docker/react/start-dev.sh:/client/start-dev.sh
      - sww-npm-node-modules:/client/node_modules
      # - sww-npm-cache:/root/.npm
    working_dir: /client
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    tty: true
    entrypoint: ./start-dev.sh

volumes:
  postgres:
  bundle-api:
  sww-npm-cache:
  sww-npm-node-modules:
