seed Needle, {metric: "1.5", uk_size: "-", us_size: "000"}
seed Needle, {metric: "2.0", uk_size: "14", us_size: "0"}
seed Needle, {metric: "2.25", uk_size: "13", us_size: "1"}
seed Needle, {metric: "2.75", uk_size: "12", us_size: "2"}
seed Needle, {metric: "3.0", uk_size: "11", us_size: "-"}
seed Needle, {metric: "3.25", uk_size: "10", us_size: "3"}
seed Needle, {metric: "3.5", uk_size: "-", us_size: "4"}
seed Needle, {metric: "3.75", uk_size: "9", us_size: "5"}
seed Needle, {metric: "4.0", uk_size: "8", us_size: "6"}
seed Needle, {metric: "4.5", uk_size: "7", us_size: "7"}
seed Needle, {metric: "5.0", uk_size: "6", us_size: "8"}
seed Needle, {metric: "5.5", uk_size: "5", us_size: "9"}
seed Needle, {metric: "6.0", uk_size: "4", us_size: "10"}
seed Needle, {metric: "6.5", uk_size: "3", us_size: "10.5"}
seed Needle, {metric: "7.0", uk_size: "2", us_size: "-"}
seed Needle, {metric: "7.5", uk_size: "1", us_size: "-"}
seed Needle, {metric: "8.0", uk_size: "0", us_size: "11"}
seed Needle, {metric: "9.0", uk_size: "00", us_size: "13"}
seed Needle, {metric: "10.0", uk_size: "000", us_size: "15"}
seed Needle, {metric: "12.0", uk_size: "-", us_size: "17"}
seed Needle, {metric: "15.0", uk_size: "-", us_size: "19"}
seed Needle, {metric: "20.0", uk_size: "-", us_size: "36"}
seed Needle, {metric: "25.0", uk_size: "-", us_size: "50"}
