seed Pattern, {name: "Basic Scarf", user_id: User.find_by(email: "admin@test.com").id}, {
  craft_type: "knitting",
  currency: "USD",
  difficulty_rating: 2,
  first_published_date: Date.new(2021, 1, 1),
  gauge_pattern: "20 sts and 28 rows = 4 inches in Stockinette Stitch",
  languages: ["en"],
  likes: 10,
  nbr_rows: 100,
  nbr_stitches: 20,
  notes: "A simple scarf pattern for beginners.",
  overall_rating: 4,
  overall_yarn_weight: "lace",
  pdf_path: "/patterns/basic_scarf.pdf",
  pictures_path: "/patterns/basic_scarf.jpg",
  price: 5.0,
  release_date: Date.new(2021, 1, 1),
  repeats: 1,
  sizes: ["XS", "S", "M", "L", "XL"],
  swatch_size: 4,
  total_yardage: 200
}

seed Pattern, {name: "Advanced Sweater", user_id: User.find_by(email: "admin@test.com").id}, {
  craft_type: "knitting",
  currency: "USD",
  difficulty_rating: 5,
  first_published_date: Date.new(2021, 2, 1),
  gauge_pattern: "18 sts and 24 rows = 4 inches in Stockinette Stitch",
  languages: ["en"],
  likes: 20,
  nbr_rows: 200,
  nbr_stitches: 30,
  notes: "A challenging sweater pattern for advanced knitters.",
  overall_rating: 5,
  overall_yarn_weight: "super_fine",
  pdf_path: "/patterns/advanced_sweater.pdf",
  pictures_path: "/patterns/advanced_sweater.jpg",
  price: 10.0,
  release_date: Date.new(2021, 2, 1),
  repeats: 2,
  sizes: ["S", "M", "L", "XL", "XXL"],
  swatch_size: 4,
  total_yardage: 400
}

seed Pattern, {name: "Simple Hat", user_id: User.find_by(email: "local@test.com").id}, {
  craft_type: "crochet",
  currency: "EUR",
  difficulty_rating: 1,
  first_published_date: Date.new(2021, 3, 1),
  gauge_pattern: "16 sts and 20 rows = 4 inches in Single Crochet",
  languages: ["en"],
  likes: 5,
  nbr_rows: 50,
  nbr_stitches: 15,
  notes: "A simple hat pattern for beginners.",
  overall_rating: 3,
  overall_yarn_weight: "fine",
  pdf_path: "/patterns/simple_hat.pdf",
  pictures_path: "/patterns/simple_hat.jpg",
  price: 3.0,
  release_date: Date.new(2021, 3, 1),
  repeats: 1,
  sizes: ["M", "L"],
  swatch_size: 4,
  total_yardage: 100
}

seed Pattern, {name: "Elegant Shawl", user_id: User.find_by(email: "local2@test.com").id}, {
  craft_type: "weaving",
  currency: "GBP",
  difficulty_rating: 4,
  first_published_date: Date.new(2021, 4, 1),
  gauge_pattern: "22 sts and 30 rows = 4 inches in Lace Weave",
  languages: ["en"],
  likes: 15,
  nbr_rows: 150,
  nbr_stitches: 25,
  notes: "An elegant shawl pattern for intermediate weavers.",
  overall_rating: 4,
  overall_yarn_weight: "light",
  pdf_path: "/patterns/elegant_shawl.pdf",
  pictures_path: "/patterns/elegant_shawl.jpg",
  price: 8.0,
  release_date: Date.new(2021, 4, 1),
  repeats: 3,
  sizes: ["XS", "L", "XXL"],
  swatch_size: 4,
  total_yardage: 300
}

seed Pattern, {name: "Cozy Blanket", user_id: User.find_by(email: "local2@test.com").id}, {
  craft_type: "knitting",
  currency: "CAD",
  difficulty_rating: 3,
  first_published_date: Date.new(2021, 5, 1),
  gauge_pattern: "12 sts and 16 rows = 4 inches in Garter Stitch",
  languages: ["en"],
  likes: 25,
  nbr_rows: 250,
  nbr_stitches: 35,
  notes: "A cozy blanket pattern for intermediate knitters.",
  overall_rating: 4,
  overall_yarn_weight: "light",
  pdf_path: "/patterns/cozy_blanket.pdf",
  pictures_path: "/patterns/cozy_blanket.jpg",
  price: 12.0,
  release_date: Date.new(2021, 5, 1),
  repeats: 4,
  sizes: ["XS", "L", "XXL"],
  swatch_size: 4,
  total_yardage: 500
}

seed Pattern, {name: "Pattern 1", user_id: User.find_by(email: "user3@test.com").id}, {
  craft_type: "knitting",
  currency: "USD",
  difficulty_rating: 3,
  first_published_date: Date.new(2021, 6, 1),
  gauge_pattern: "20 sts and 28 rows = 4 inches in Stockinette Stitch",
  languages: ["en"],
  likes: 30,
  nbr_rows: 120,
  nbr_stitches: 25,
  notes: "Pattern 1 notes.",
  overall_rating: 4,
  overall_yarn_weight: "light",
  pdf_path: "/patterns/pattern1.pdf",
  pictures_path: "/patterns/pattern1.jpg",
  price: 6.0,
  release_date: Date.new(2021, 6, 1),
  repeats: 2,
  sizes: ["S", "M", "L"],
  swatch_size: 4,
  total_yardage: 250
}

seed Pattern, {name: "Pattern 2", user_id: User.find_by(email: "user4@test.com").id}, {
  craft_type: "crochet",
  currency: "EUR",
  difficulty_rating: 2,
  first_published_date: Date.new(2021, 7, 1),
  gauge_pattern: "18 sts and 24 rows = 4 inches in Single Crochet",
  languages: ["en"],
  likes: 15,
  nbr_rows: 80,
  nbr_stitches: 20,
  notes: "Pattern 2 notes.",
  overall_rating: 3,
  overall_yarn_weight: "light",
  pdf_path: "/patterns/pattern2.pdf",
  pictures_path: "/patterns/pattern2.jpg",
  price: 4.0,
  release_date: Date.new(2021, 7, 1),
  repeats: 1,
  sizes: ["M", "L"],
  swatch_size: 4,
  total_yardage: 150
}
